#!/usr/bin/env bash
# Local Ironman API deploy via Pulumi (no GitHub OIDC).
# Usage:
#   export AWS_PROFILE=umesh          # or your profile
#   export IRONMAN_PIN=XXXX           # 4 digits; never commit
#   ./deploy.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

AWS_REGION="${AWS_REGION:-ap-south-1}"
AWS_PROFILE="${AWS_PROFILE:-umesh}"
PULUMI_BACKEND_URL="${PULUMI_BACKEND_URL:-s3://skalekontrol/pulumi/ironman}"
STACK="${PULUMI_STACK:-ironman}"

# DIY S3 backend: empty passphrase — no interactive unlock prompts.
export PULUMI_CONFIG_PASSPHRASE=""

export AWS_PROFILE
export AWS_REGION
export AWS_DEFAULT_REGION="$AWS_REGION"

if [ -z "${IRONMAN_PIN:-}" ]; then
  echo "Set IRONMAN_PIN to your 4-digit PIN (not stored in git)." >&2
  exit 1
fi
if ! [[ "$IRONMAN_PIN" =~ ^[0-9]{4}$ ]]; then
  echo "IRONMAN_PIN must be exactly 4 digits." >&2
  exit 1
fi

echo "==> AWS identity ($AWS_PROFILE)"
aws sts get-caller-identity

echo "==> npm install + Lambda bundle"
npm install
npm run build:lambda

echo "==> Pulumi login ($PULUMI_BACKEND_URL)"
pulumi login "$PULUMI_BACKEND_URL"
pulumi stack select "$STACK" --create

pulumi config set aws:region "$AWS_REGION"
pulumi config set --secret ironmanPin "$IRONMAN_PIN"

echo "==> pulumi up"
pulumi up --yes

echo "==> Write api-config.js"
# Use JSON output so the URL is never word-split by the shell
API_URL="$(pulumi stack output apiUrl --stack "$STACK" --json | sed -e 's/^"//' -e 's/"$//')"
API_URL="${API_URL%/}"
if [ -z "$API_URL" ] || [ "$API_URL" = "null" ]; then
  echo "Could not resolve apiUrl output" >&2
  exit 1
fi

# Quoted heredoc delimiter — only substitute via printf to avoid shell eval surprises
printf '%s\n' \
  '// Generated by ironman/api/deploy.sh. Do not put the PIN here.' \
  'window.IRONMAN_API = {' \
  "  baseUrl: '${API_URL}'," \
  '};' \
  > ../api-config.js

echo "==> Wrote ../api-config.js"
cat ../api-config.js
echo "==> Done"
